name: Deploy to GitHub Pages

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: true
          fetch-depth: 0

      - uses: subosito/flutter-action@88cab4064b0a5145b0b53b42565b68248a3d7bcb

      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool

      - name: Build
        run: dart run _tool/build_ci.dart
        working-directory: web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/samples_index/public
