name: Verify web demos

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-web-demos:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    strategy:
      matrix:
        flutter_version:
          - stable
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          submodules: true
          fetch-depth: 0
      - uses: subosito/flutter-action@1e6ee87cb840500837bcd50a667fb28815d8e310
        with:
          channel: ${{ matrix.flutter_version }}
      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool
      - name: Verify packages
        run: dart _tool/verify_packages.dart
        working-directory: web
